version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: next-tag
    volumes:
      - ./frontend:/my-project
      - ./videos:/videos
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - local

  api:
    build:
      dockerfile: Dockerfile
      context: ./Api
    container_name: api-rpg
    restart: always
    volumes:
      - "./Api:/app"
    environment:
      ENV: "docker"
    ports: 
      - 3001:3000
    depends_on:
      - db
      - cache
    networks:
      - local
  cache:
    image: redis
    container_name: redis-rpg
    ports:
     - "6379:6379"
    networks:
      - local
  db:
    image: mariadb:10.2
    container_name: database-rpg
    restart: always
    environment:
      MYSQL_USER: "uroot"
      MYSQL_PASSWORD: "example"
      MYSQL_DATABASE: "test02"
      MYSQL_ROOT_PASSWORD: "example"
    ports:
      - 3306:3306
    volumes:
      - "./init:/docker-entrypoint-initdb.d"    
    networks:
      - local
  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - 8080:8080
    networks:
      - local
networks:
  local:
    driver: bridge

